/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ULRyeKTY9hV
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function landing() {
  return (
    <div className="flex flex-col min-h-screen justify-center"> 
      <header className="py-4 md:py-6">
        <div className="container flex items-center justify-between px-4 md:px-6">
          <Link className="flex items-center space-x-2" href="#">
            <SquareIcon className="h-6 w-6" />
            <span className="font-bold">Shape</span>
          </Link>
          <nav className="hidden md:flex items-center space-x-4">
            <Link className="font-medium tracking-wide hover:underline" href="#">
              Features
            </Link>
            <Link className="font-medium tracking-wide hover:underline" href="#">
              Pricing
            </Link>
            <Link className="font-medium tracking-wide hover:underline" href="#">
              Contact
            </Link>
          </nav>
          <div className="flex items-center space-x-4">
            <Link
              className="inline-flex items-center space-x-2 text-sm font-medium tracking-tighter rounded-lg bg-gray-100 px-3 py-1 hover:bg-gray-100/90 dark:bg-gray-800 dark:hover:bg-gray-800/90"
              href="#"
            >
              <UserIcon className="h-4 w-4" />
              Sign Up
            </Link>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="bg-gray-900 py-12 md:py-24 lg:py-32 text-gray-100 dark:bg-gray-100 dark:text-gray-900">
          <div className="container flex flex-col items-center justify-center px-4 space-y-4 md:px-6 lg:space-y-8">
            <div className="text-center">
              <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl md:text-6xl/none">
                Shape Success
                <span className="bg-clip-text text-transparent bg-gradient-to-r from-yellow-300 to-yellow-500 via-yellow-400 dark:from-amber-300 dark:to-amber-500 dark:via-amber-400">
                  Snip by Snip
                </span>
              </h1>
              <p className="mx-auto max-w-[600px] text-gray-300 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                The platform for rapid progress. Let your team focus on shipping features instead of managing
                infrastructure with automated CI/CD, built-in testing, and integrated collaboration.
              </p>
            </div>
          </div>
        </section>
        <section className="grid gap-12 py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="grid items-center gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
              <img
                alt="Image"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                    Faster iteration. More innovation.
                  </h2>
                  <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                    The platform for rapid progress. Let your team focus on shipping features instead of managing
                    infrastructure with automated CI/CD, built-in testing, and integrated collaboration.
                  </p>
                </div>
                <ul className="grid gap-2 py-4">
                  <li>
                    <CheckIcon className="mr-2 inline-block h-4 w-4" />
                    Make collaboration seamless with built-in code review tools.
                  </li>
                  <li>
                    <CheckIcon className="mr-2 inline-block h-4 w-4" />
                    Automate your workflow with continuous integration and delivery.
                  </li>
                  <li>
                    <CheckIcon className="mr-2 inline-block h-4 w-4" />
                    Deploy to the cloud with a single click and scale with ease.
                  </li>
                </ul>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                    href="#"
                  >
                    Contact Sales
                  </Link>
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                    href="#"
                  >
                    Tour the Platform
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="border-t">
          <div className="container flex flex-col items-center justify-center py-12 md:py-24 lg:py-32 px-4 md:px-6 space-y-4">
            <div className="space-y-2 text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">The Platform for Rapid Progress</h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Let your team focus on shipping features instead of managing infrastructure with automated CI/CD,
                built-in testing, and integrated collaboration.
              </p>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container flex flex-col items-center justify-center space-y-4 px-4 md:px-6 mx-auto">
            <div className="space-y-2 text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Features to Accelerate Innovation</h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                The platform for rapid progress. Let your team focus on shipping features instead of managing
                infrastructure with automated CI/CD, built-in testing, and integrated collaboration.
              </p>
            </div>
            <div className="grid gap-12 md:gap-24 lg:grid-cols-2 lg:gap-16">
              <div className="flex flex-col items-center space-y-2">
                <CheckCircleIcon className="h-10 w-10" />
                <div className="space-y-2 text-center">
                  <h3 className="font-bold">Collaboration</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Make collaboration seamless with built-in code review tools.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <CheckCircleIcon className="h-10 w-10" />
                <div className="space-y-2 text-center">
                  <h3 className="font-bold">Automation</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Automate your workflow with continuous integration and delivery.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <CheckCircleIcon className="h-10 w-10" />
                <div className="space-y-2 text-center">
                  <h3 className="font-bold">Deployment</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Deploy to the cloud with a single click and scale with ease.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container flex flex-col items-center justify-center space-y-4 px-4 md:px-6">
            <div className="space-y-2 text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Features to Accelerate Innovation</h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                The platform for rapid progress. Let your team focus on shipping features instead of managing
                infrastructure with automated CI/CD, built-in testing, and integrated collaboration.
              </p>
            </div>
            <div className="grid gap-12 md:gap-24 lg:grid-cols-2 lg:gap-16">
              <div className="flex flex-col items-center space-y-2">
                <CheckCircleIcon className="h-10 w-10" />
                <div className="space-y-2 text-center">
                  <h3 className="font-bold">Collaboration</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Make collaboration seamless with built-in code review tools.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <CheckCircleIcon className="h-10 w-10" />
                <div className="space-y-2 text-center">
                  <h3 className="font-bold">Automation</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Automate your workflow with continuous integration and delivery.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <CheckCircleIcon className="h-10 w-10" />
                <div className="space-y-2 text-center">
                  <h3 className="font-bold">Deployment</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Deploy to the cloud with a single click and scale with ease.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container flex flex-col items-center justify-center space-y-4 px-4 md:px-6 mx-auto">
            <div className="space-y-2 text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Features to Accelerate Innovation</h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                The platform for rapid progress. Let your team focus on shipping features instead of managing
                infrastructure with automated CI/CD, built-in testing, and integrated collaboration.
              </p>
            </div>
            <div className="grid gap-12 md:gap-24 lg:grid-cols-2 lg:gap-16">
              <div className="flex flex-col items-center space-y-2">
                <CheckCircleIcon className="h-10 w-10" />
                <div className="space-y-2 text-center">
                  <h3 className="font-bold">Collaboration</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Make collaboration seamless with built-in code review tools.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <CheckCircleIcon className="h-10 w-10" />
                <div className="space-y-2 text-center">
                  <h3 className="font-bold">Automation</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Automate your workflow with continuous integration and delivery.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <CheckCircleIcon className="h-10 w-10" />
                <div className="space-y-2 text-center">
                  <h3 className="font-bold">Deployment</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Deploy to the cloud with a single click and scale with ease.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-24 lg:py-32">
          <div className="container flex flex-col items-center justify-center space-y-4 px-4 md:px-6 mx-auto">
            <div className="space-y-2 text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Features to Accelerate Innovation</h2>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                The platform for rapid progress. Let your team focus on shipping features instead of managing
                infrastructure with automated CI/CD, built-in testing, and integrated collaboration.
              </p>
            </div>
            <div className="grid gap-12 md:gap-24 lg:grid-cols-2 lg:gap-16">
              <div className="flex flex-col items-center space-y-2">
                <CheckCircleIcon className="h-10 w-10" />
                <div className="space-y-2 text-center">
                  <h3 className="font-bold">Collaboration</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Make collaboration seamless with built-in code review tools.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <CheckCircleIcon className="h-10 w-10" />
                <div className="space-y-2 text-center">
                  <h3 className="font-bold">Automation</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Automate your workflow with continuous integration and delivery.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <CheckCircleIcon className="h-10 w-10" />
                <div className="space-y-2 text-center">
                  <h3 className="font-bold">Deployment</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Deploy to the cloud with a single click and scale with ease.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="border-t">
        <div className="container flex flex-col items-center justify-center py-12 md:py-24 lg:py-32 px-4 md:px-6 space-y-4 mx-auto">
          <div className="space-y-2 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Features to Accelerate Innovation</h2>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              The platform for rapid progress. Let your team focus on shipping features instead of managing
              infrastructure with automated CI/CD, built-in testing, and integrated collaboration.
            </p>
          </div>
          <form className="flex flex-col gap-2 max-[400px]:flex-row">
            <Input className="w-full sm:max-w-[250px]" placeholder="Enter your email" type="email" />
            <Button className="w-full sm:max-w-[150px]" type="submit">
              Sign Up
            </Button>
          </form>
        </div>
        <div className="bg-gray-100">
          <div className="container flex items-center justify-between px-4 md:px-6 mx-auto">
            <span className="text-sm text-gray-500 dark:text-gray-400">© 2023 Shape. All rights reserved.</span>
            <nav className="flex items-center space-x-4">
              <Link className="font-medium tracking-wide hover:underline" href="#">
                Features
              </Link>
              <Link className="font-medium tracking-wide hover:underline" href="#">
                Pricing
              </Link>
              <Link className="font-medium tracking-wide hover:underline" href="#">
                Contact
              </Link>
            </nav>
          </div>
        </div>
      </footer>
    </div>
  )
}


function SquareIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
    </svg>
  )
}


function UserIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function CheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  )
}


function CheckCircleIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  )
}
