/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fePK42tEkRg
 */
import { CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function login() {
  return (
    <Card key="1" className="w-full max-w-md mx-auto">
      <CardHeader className="text-center">
        <h1 className="text-3xl">Welcome to HairHaven</h1>
        <CardDescription>Enter your credentials below</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="username">Username</Label>
          <Input id="username" placeholder="Username" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="password">Password</Label>
          <Input id="password" placeholder="Password" required type="password" />
        </div>
        <Button className="w-full" type="submit">
          Login
        </Button>
      </CardContent>
      <CardFooter className="text-center">
        <Button className="w-full" variant="outline">
          Login with Google
        </Button>
        <div className="mt-4">
          <Link className="underline" href="#">
            Forgot your password?
          </Link>
        </div>
      </CardFooter>
    </Card>
  )
}
