/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/29wKroEkTBQ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function mobile() {
  return (
    <div className="flex flex-col min-h-screen bg-black text-white">
      <div className="flex flex-col items-center py-5">
        <Avatar className="mb-4">
          <AvatarImage alt="Profile picture" src="/placeholder.svg?height=100&width=100" />
          <AvatarFallback>KS</AvatarFallback>
        </Avatar>
        <h1 className="text-3xl font-semibold text-gold-500">Konstantin Shelby</h1>
      </div>
      <main className="flex-1 p-5 space-y-6">
        <section className="bg-[#1a1a1a] p-4 rounded-md">
          <h2 className="text-xl font-bold mb-3 text-gold-500">Details</h2>
          <p>
            Konstantin Shelby <Badge variant="secondary">verified</Badge>
          </p>
          <p>Account verification: verified</p>
          <p>Referral program: active</p>
          <p>Account ID: 73579</p>
        </section>
        <section className="bg-[#1a1a1a] p-4 rounded-md grid grid-cols-1 md:grid-cols-2 gap-6">
          <div>
            <h2 className="text-xl font-bold mb-3 text-gold-500">Barbers Connected</h2>
            <ul>
              <li className="mb-2">
                <div className="flex items-center justify-between">
                  <span>Tom Hardy</span>
                  <Badge>Latest haircut: March 15, 2023</Badge>
                </div>
              </li>
              <li className="mb-2">
                <div className="flex items-center justify-between">
                  <span>Cillian Murphy</span>
                  <Badge>Latest haircut: April 22, 2023</Badge>
                </div>
              </li>
            </ul>
          </div>
          <div>
            <h2 className="text-xl font-bold mb-3 text-gold-500">Hair Visualizations</h2>
            <img
              alt="Haircut inspiration"
              className="rounded-md"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
          </div>
        </section>
        <section className="bg-[#1a1a1a] p-4 rounded-md">
          <h2 className="text-xl font-bold mb-3 text-gold-500">Hair Inputs</h2>
          <form>
            <div className="mb-4">
              <Label className="text-gold-500" htmlFor="hair-type">
                Identified Hair Type
              </Label>
              <Input className="mt-1 bg-white text-black" id="hair-type" placeholder="Enter hair type" />
            </div>
            <div className="mb-4">
              <Label className="text-gold-500" htmlFor="hair-prompt">
                Hair Style Prompt
              </Label>
              <Textarea
                className="mt-1 bg-white text-black min-h-[100px]"
                id="hair-prompt"
                placeholder="Enter style prompt"
              />
            </div>
            <Button className="w-full" variant="secondary">
              Get Recommendations
            </Button>
          </form>
        </section>
        <section className="bg-[#1a1a1a] p-4 rounded-md">
          <h2 className="text-xl font-bold mb-3 text-gold-500">Generated Recommendations</h2>
          <p>
            You have a lovely curl pattern that can be enhanced with the right cut. It looks like you have a versatile
            face shape that's somewhere between oval and round, which gives you quite a few options for flattering
            hairstyles. For your face shape, you can balance your features with a cut that is shorter on the sides and
            back, while leaving length on top to take advantage of your curl pattern.
          </p>
        </section>
      </main>
    </div>
  )
}
