/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/PvAz9MCRhQS
 */
import { Button } from "@/app/dashboard/ui/button"
import { CardContent, Card } from "@/app/dashboard/ui/card"
import { Calendar } from "@/app/dashboard/ui/calendar"

export function upcoming() {
  return (
    <div key="1" className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <div className="space-y-1">
            <h2 className="text-lg font-bold">Hi, Barber</h2>
            <p className="text-sm text-gray-500 dark:text-gray-400">You have 3 upcoming appointments</p>
          </div>
          <Button size="sm">View Profile</Button>
        </div>
        <Card>
          <CardContent className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <img
                alt="Avatar"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="space-y-1">
                <h3 className="text-sm font-bold">Alice Johnson</h3>
                <p className="text-xs text-gray-500 dark:text-gray-400">Next appointment: 12th Aug, 10:00 AM</p>
              </div>
            </div>
            <Button className="rounded-full" size="icon">
              <ChevronRightIcon className="w-4 h-4" />
              <span className="sr-only">View</span>
            </Button>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <img
                alt="Avatar"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="space-y-1">
                <h3 className="text-sm font-bold">Bob Smith</h3>
                <p className="text-xs text-gray-500 dark:text-gray-400">Next appointment: 15th Aug, 11:00 AM</p>
              </div>
            </div>
            <Button className="rounded-full" size="icon">
              <ChevronRightIcon className="w-4 h-4" />
              <span className="sr-only">View</span>
            </Button>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <img
                alt="Avatar"
                className="rounded-full"
                height="40"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width="40"
              />
              <div className="space-y-1">
                <h3 className="text-sm font-bold">Charlie Brown</h3>
                <p className="text-xs text-gray-500 dark:text-gray-400">Next appointment: 20th Aug, 09:00 AM</p>
              </div>
            </div>
            <Button className="rounded-full" size="icon">
              <ChevronRightIcon className="w-4 h-4" />
              <span className="sr-only">View</span>
            </Button>
          </CardContent>
        </Card>
      </div>
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <div className="space-y-1">
            <h2 className="text-lg font-bold">Appointments</h2>
            <p className="text-sm text-gray-500 dark:text-gray-400">Click on a day to view appointments</p>
          </div>
          <Button size="sm">New Appointment</Button>
        </div>
        <Card>
          <CardContent className="p-0">
            <Calendar />
          </CardContent>
        </Card>
      </div>
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <div className="space-y-1">
            <h2 className="text-lg font-bold">Hair Visualizer</h2>
            <p className="text-sm text-gray-500 dark:text-gray-400">Visualize different hairstyles</p>
          </div>
          <Button size="sm">Save</Button>
        </div>
        <Card>
          <CardContent className="p-0">
            <div className="flex justify-center p-4 border-dashed border-2 border-gray-200 rounded-lg dark:border-gray-800">
              <img
                alt="Hair Visualizer"
                className="aspect-[4/3] overflow-hidden rounded-lg object-cover"
                height="300"
                src="/placeholder.svg"
                width="400"
              />
            </div>
          </CardContent>
        </Card>
      </div>
      <div className="space-y-6">
        <div className="flex items-center gap-4">
          <div className="space-y-1">
            <h2 className="text-lg font-bold">Haircut History</h2>
            <p className="text-sm text-gray-500 dark:text-gray-400">View past haircuts and comments</p>
          </div>
          <Button size="sm">Add New</Button>
        </div>
        <Card>
          <CardContent className="p-0">
            <div className="grid gap-4 sm:grid-cols-2">
              <div className="flex items-center gap-4">
                <img
                  alt="Haircut"
                  className="rounded-lg object-cover"
                  height="150"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "150/150",
                    objectFit: "cover",
                  }}
                  width="150"
                />
                <div className="space-y-2">
                  <div className="flex items-center gap-4">
                    <CalendarIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                    <p className="text-sm text-gray-500 dark:text-gray-400">12th Aug 2023</p>
                  </div>
                  <div className="flex items-center gap-4">
                    <UserIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                    <p className="text-sm text-gray-500 dark:text-gray-400">Stylist: Alice Johnson</p>
                  </div>
                  <div className="flex items-center gap-4">
                    <ScissorsIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
                    <p className="text-sm text-gray-500 dark:text-gray-400">Style: Layered Cut</p>
                  </div>
                </div>
              </div>
              <div className="space-y-4">
                <h3 className="text-lg font-bold">Comments</h3>
                <p className="text-sm text-gray-500 dark:text-gray-400">Customer wants a shorter cut next time</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}


function ChevronRightIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m9 18 6-6-6-6" />
    </svg>
  )
}


function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}


function ScissorsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="6" cy="6" r="3" />
      <path d="M8.12 8.12 12 12" />
      <path d="M20 4 8.12 15.88" />
      <circle cx="6" cy="18" r="3" />
      <path d="M14.8 14.8 20 20" />
    </svg>
  )
}
