/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mxtVVRfzkBH
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Calendar } from "@/components/ui/calendar"
import { Textarea } from "@/components/ui/textarea"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import React, { useState } from "react"

export default function exampleprofile() {
  const [hairstyle, setHairstyle] = useState("")

  return (
        <main className="flex-1 p-5">
          <div className="flex justify-between mb-5">
            <h1 className="text-xl font-semibold">Om Joshi</h1>
            {/* <Button variant="outline">Sign Out</Button> */}
          </div>
          <div className="grid grid-cols-3 gap-4">
          <Card className="col-span-1">
              <CardHeader>
                <CardTitle>Past Customer Ratings</CardTitle>
              </CardHeader>
              <CardContent>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Date</TableHead>
                      <TableHead>Service</TableHead>
                      <TableHead>Rating</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell>April 15, 2023</TableCell>
                      <TableCell>Style Update</TableCell>
                      <TableCell>5/10 - Cut my hair too short right before an interview.</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>March 10, 2023</TableCell>
                      <TableCell>Complete Makeover</TableCell>
                      <TableCell>10/10 - Knew exactly what I was talking about, and got the job done quick.</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>March 10, 2023</TableCell>
                      <TableCell>Complete Makeover</TableCell>
                      <TableCell>10/10 - Knew exactly what I was talking about, and got the job done quick.</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>March 10, 2023</TableCell>
                      <TableCell>Complete Makeover</TableCell>
                      <TableCell>10/10 - Knew exactly what I was talking about, and got the job done quick.</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </CardContent>
              
            </Card>
            <Card className="col-span-1">
              <CardHeader>
                <CardTitle>Upcoming Schedule</CardTitle>
              </CardHeader>
              <CardContent>
                <Calendar className="rounded-md border border-gray-200 mb-4 dark:border-gray-800" mode="single" />
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <h3 className="font-semibold mb-2">Upcoming Visits</h3>
                    <ul>
                      <li className="mb-2">10:00 AM - Trim</li>
                      <li className="mb-2">5:00 PM - Taper, Fade</li>
                    </ul>
                  </div>
                  {/* <div>
                    <h3 className="font-semibold mb-2">Special Visits</h3>
                    <ul>
                      <li className="mb-2">May 10, 2024 - Prom Event</li>
                      <li className="mb-2">May 15, 2024 - Wedding Contract</li>
                    </ul>
                  </div> */}
                </div>
              </CardContent>
            </Card>
            
            <Card className="col-span-1">
              <CardHeader>
                <CardTitle>10:00AM - Konstantine Shelby</CardTitle>
                <p> </p>
                <div>
                    <h3 className="font-semibold mb-2">Most Recent Visualization</h3>
                    <div className="mt-4 flex justify-start">
                      <Button className="bg-[#ffd700] text-black" onClick={() => setHairstyle("afro")}>Access Afro Visualization</Button>
                    </div>
                    <div className="mt-4 flex justify-start" style={{paddingBottom: 20}} >
                      <Button className="bg-[#ffd700] text-black" onClick={() => setHairstyle("nvm")}>Access Bowl Cut Visualization</Button>
                    </div>
                    <ul>
                      <li className="mb-2">2/14/24 - Afro Hairstyle</li>
                      <li className="mb-2">3/16/23 - Short Bowl Cut</li>
                    </ul>
                    {hairstyle === "afro" ? (
                    <video controls>
                      <source src="hairstyle1.mp4" type="video/mp4" />
                      Your browser does not support the video tag.
                    </video>
                  ) : null}
                  {hairstyle === "nvm" ? (
                    <video controls>
                      <source src="hairstyle3.mp4" type="video/mp4" />
                      Your browser does not support the video tag.
                    </video>
                  ) : null}
                  </div>
                <div>
                      <h3 className="font-semibold mb-2">Upcoming Visits</h3>
                      <ul>
                        <li className="mb-2">10:00 AM - Trim</li>
                        <li className="mb-2">5:00 PM - Taper, Fade</li>
                    </ul>
                  </div>
              <div className="mt-4 flex justify-center" style={{ paddingBottom: 30 }}>
                <Button className="bg-[#ffd700] text-black">Access Profile</Button>
              </div>
              </CardHeader>
            </Card>
            
            <Card className="col-span-3">
              <CardHeader>
                <CardTitle>
                  Query Customer Data</CardTitle>
                <p> </p>
                <p className="text-sm">
                </p>
              </CardHeader>
              <CardContent>
                <Textarea placeholder="Ask questions regarding feedback from your customers." />
              </CardContent>

              <div className="mt-4 flex justify-center" style={{ paddingBottom: 30 }}>
                <Button className="bg-[#ffd700] text-black">Get Data</Button>
              </div>
            </Card>
          </div>
        </main>
  )
}


function MoreVerticalIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="1" />
      <circle cx="12" cy="5" r="1" />
      <circle cx="12" cy="19" r="1" />
    </svg>
  )
}