
'use client'
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kwCJPkUVjg2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*
*/
import Search from './search'
import React, { useState } from 'react';
import { signOut, useSession } from "next-auth/react";
import Profile from './profile'
import Customer from './second-profile'

export default function search() {
    const [state, setState] = useState("Dashboard");

    return (
      <div className="min-h-screen bg-white text-black">
        <div className="flex">
          <aside className="w-60 bg-white p-5 border-r border-gray-200">
            <div className="mb-10" >
              <img alt="Logo" className="h-8" src="/logo.png" style={{borderRadius: "20%"}}/>
            </div>
            <ul className="space-y-2">
                {state === "Dashboard" ? (
                    <li onClick={() => setState("Dashboard")}>
                        <a className="block p-2 bg-gray-200" href="#">
                            Dashboard
                        </a>
                    </li>
                ) : (
                    <li onClick={() => setState("Dashboard")}>
                        <a className="block p-2 hover:bg-gray-200" href="#">
                            Dashboard
                        </a>
                    </li>
                )}
                {state === "Profile" ? (
                    <li onClick={() => setState("Profile")}>
                        <a className="block p-2 bg-gray-200" href="#">
                            Customer Search
                        </a>
                    </li>
                ) : (
                    <li onClick={() => setState("Profile")}>
                        <a className="block p-2 hover:bg-gray-200" href="#">
                            Customer Search
                        </a>
                    </li>
                )}
                {state === "Customer Profile" ? (
                    <li onClick={() => setState("Customer Profile")}>
                        <a className="block p-2 bg-gray-200" href="#">
                            Customer Profile
                        </a>
                    </li>
                ) : (
                    <li onClick={() => setState("Customer Profile")}>
                        <a className="block p-2 hover:bg-gray-200" href="#">
                            Customer Profile
                        </a>
                    </li>
                )}
                {state === "Calendar" ? (
                    <li onClick={() => setState("Calendar")}>
                        <a className="block p-2 bg-gray-200" href="#">
                            Finances
                        </a>
                    </li>
                ) : (
                    <li onClick={() => setState("Calendar")}>
                        <a className="block p-2 hover:bg-gray-200" href="#">
                            Finances
                        </a>
                    </li>
                )}
                {state === "Settings" ? (
                    <li onClick={() => setState("Settings")}>
                        <a className="block p-2 bg-gray-200" href="#">
                            Settings
                        </a>
                    </li>
                ) : (
                    <li onClick={() => setState("Settings")}>
                        <a className="block p-2 hover:bg-gray-200" href="#">
                            Settings
                        </a>
                    </li>
                )}

              {/* <li onClick={() => setState("Dashboard")}>
                <a className="block p-2 hover:bg-gray-200" href="#">
                  Dashboard
                </a>
              </li>
              <li  onClick={() => setState("Profile")}>
                <a className="block p-2 hover:bg-gray-200" href="#">
                  Profile
                </a>
              </li>
              <li onClick={() => setState("Customers")}>
                <a className="block p-2 bg-gray-200" href="#">
                  Customers
                </a>
              </li>
              <li onClick={() => setState("Calendar")}>
                <a className="block p-2 hover:bg-gray-200" href="#">
                  Calendar
                </a>
              </li>
              <li onClick={() => setState("Settings")}>
                <a className="block p-2 hover:bg-gray-200" href="#">
                  Settings
                </a>
              </li> */}
            </ul>
            <div className="mt-auto" onClick = {() => signOut()}>
              <button className="text-left w-full p-2 hover:bg-gray-200">Sign Out</button>
            </div>
          </aside>
          {state == "Dashboard" ? <Profile/> : <></> }
        {state == "Profile" ? <Search/> : <></> }
        {state == "Customer Profile" ? <Customer/> : <></> }
        {/* {state == "Calendar" ? <Calendar/> : <></> } */} 
        {state == "Settings" ? <></> : <></> }
            </div>
      </div>
    )
  }
  