/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kwCJPkUVjg2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export default function search() {
  return (
    <div className="min-h-screen bg-white text-black h-full col-span-3">
      <div className="flex-3 h-full">
        <main className="flex-3 p-8 h-full">
          <div className="flex justify-between items-center mb-6 h-full">
            <h1 className="text-2xl font-semibold">Customers</h1>
            <div className="flex space-x-2">
              <input className="px-3 py-2 bg-gray-200" placeholder="Search customers" type="text" />
              <button className="bg-gray-200 px-3 py-2">Search</button>
            </div>
          </div>
          <div className="space-y-4">
            <div className="overflow-y-auto max-h-[480px]">
              <div className="flex items-center bg-black text-white p-4 rounded-md">
                <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center">
                  <span className="text-black font-semibold">JD</span>
                </div>
                <div className="ml-4">
                  <div className="text-lg font-medium">John Doe</div>
                  <div className="text-white text-sm">Last haircut: March 10, 2023 | Next haircut: April 5, 2023</div>
                </div>
              </div>
              <div className="h-4" />
              <div className="flex items-center bg-black text-white p-4 rounded-md">
                <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center">
                  <span className="text-black font-semibold">JS</span>
                </div>
                <div className="ml-4">
                  <div className="text-lg font-medium">Jane Smith</div>
                  <div className="text-white text-sm">Last haircut: New customer | Next haircut: TBD</div>
                </div>
              </div>
              <div className="h-4" />
              <div className="flex items-center bg-black text-white p-4 rounded-md">
                <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center">
                  <span className="text-black font-semibold">KS</span>
                </div>
                <div className="ml-4">
                  <div className="text-lg font-medium">Konstantin Shelby</div>
                  <div className="text-white text-sm">Last haircut: TBD | Next haircut: TBD</div>
                </div>
              </div>
              <div className="h-4" />
              <div className="flex items-center bg-black text-white p-4 rounded-md">
                <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center">
                  <span className="text-black font-semibold">AB</span>
                </div>
                <div className="ml-4">
                  <div className="text-lg font-medium">Alice Brown</div>
                  <div className="text-white text-sm">Last haircut: April 1, 2023 | Next haircut: April 25, 2023</div>
                </div>
              </div>
              <div className="h-4" />
              <div className="flex items-center bg-black text-white p-4 rounded-md">
                <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center">
                  <span className="text-black font-semibold">CD</span>
                </div>
                <div className="ml-4">
                  <div className="text-lg font-medium">Chris Davis</div>
                  <div className="text-white text-sm">Last haircut: March 15, 2023 | Next haircut: April 10, 2023</div>
                </div>
              </div>
              <div className="h-4" />
              <div className="flex items-center bg-black text-white p-4 rounded-md">
                <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center">
                  <span className="text-black font-semibold">EF</span>
                </div>
                <div className="ml-4">
                  <div className="text-lg font-medium">Emily Foster</div>
                  <div className="text-white text-sm">Last haircut: TBD | Next haircut: TBD</div>
                </div>
              </div>
              <div className="h-4" />
              <div className="flex items-center bg-black text-white p-4 rounded-md">
                <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center">
                  <span className="text-black font-semibold">GH</span>
                </div>
                <div className="ml-4">
                  <div className="text-lg font-medium">George Harrison</div>
                  <div className="text-white text-sm">
                    Last haircut: February 28, 2023 | Next haircut: March 25, 2023
                  </div>
                </div>
              </div>
              <div className="h-4" />
              <div className="flex items-center bg-black text-white p-4 rounded-md">
                <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center">
                  <span className="text-black font-semibold">IJ</span>
                </div>
                <div className="ml-4">
                  <div className="text-lg font-medium">Isabel Jones</div>
                  <div className="text-white text-sm">Last haircut: TBD | Next haircut: TBD</div>
                </div>
              </div>
              <div className="h-4" />
              <div className="flex items-center bg-black text-white p-4 rounded-md">
                <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center">
                  <span className="text-black font-semibold">KL</span>
                </div>
                <div className="ml-4">
                  <div className="text-lg font-medium">Kevin Lee</div>
                  <div className="text-white text-sm">
                    Last haircut: January 20, 2023 | Next haircut: February 15, 2023
                  </div>
                </div>
              </div>
              <div className="h-4" />
              <div className="flex items-center bg-black text-white p-4 rounded-md">
                <div className="w-10 h-10 bg-white rounded-full flex items-center justify-center">
                  <span className="text-black font-semibold">MN</span>
                </div>
                <div className="ml-4">
                  <div className="text-lg font-medium">Mary Nelson</div>
                  <div className="text-white text-sm">Last haircut: TBD | Next haircut: TBD</div>
                </div>
              </div>
              <div className="h-4" />
            </div>
          </div>
        </main>
      </div>
    </div>
  )
}
